"""Update chunk table columns

Revision ID: 0b810fcbcd2e
Revises: 787edeee99ca
Create Date: 2025-09-28 16:51:41.803143

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector




# revision identifiers, used by Alembic.
revision: str = '0b810fcbcd2e'
down_revision: Union[str, Sequence[str], None] = '787edeee99ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('size', sa.Integer(), nullable=False))
    op.add_column('chunk', sa.Column('order', sa.Integer(), nullable=False))
    op.add_column('chunk', sa.Column('page', sa.Integer(), nullable=False))
    op.drop_column('chunk', 'chunk_size')
    op.drop_column('chunk', 'chunk_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('chunk_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chunk', sa.Column('chunk_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('chunk', 'page')
    op.drop_column('chunk', 'order')
    op.drop_column('chunk', 'size')
    # ### end Alembic commands ###
