"""Add author and summary column to Document table

Revision ID: 17f822876cba
Revises: fa2967800fc5
Create Date: 2025-11-13 14:53:05.993098

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector




# revision identifiers, used by Alembic.
revision: str = '17f822876cba'
down_revision: Union[str, Sequence[str], None] = 'fa2967800fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('document', sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'summary')
    op.drop_column('document', 'author')
    # ### end Alembic commands ###
