"""Add authors to Document table

Revision ID: 212baf21adf0
Revises: 17f822876cba
Create Date: 2025-11-13 16:49:09.288316

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector




# revision identifiers, used by Alembic.
revision: str = '212baf21adf0'
down_revision: Union[str, Sequence[str], None] = '17f822876cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('authors', sa.JSON(), server_default='[]', nullable=False))
    op.drop_column('document', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('document', 'authors')
    # ### end Alembic commands ###
