"""AddCascadeInChunk

Revision ID: 787edeee99ca
Revises: b3366018f2cb
Create Date: 2025-08-31 18:41:39.365579

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector




# revision identifiers, used by Alembic.
revision: str = '787edeee99ca'
down_revision: Union[str, Sequence[str], None] = 'b3366018f2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chunk_document_id_fkey'), 'chunk', type_='foreignkey')
    op.create_foreign_key(None, 'chunk', 'document', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chunk', type_='foreignkey')
    op.create_foreign_key(op.f('chunk_document_id_fkey'), 'chunk', 'document', ['document_id'], ['id'])
    # ### end Alembic commands ###
