"""Update MessageRole enum

Revision ID: 84bf5de77bfb
Revises: 212baf21adf0
Create Date: 2025-11-17 21:20:00.929013

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '84bf5de77bfb'
down_revision: Union[str, Sequence[str], None] = '212baf21adf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='messagerole',
        new_values=['USER', 'SYSTEM', 'ASSISTANT'],
        affected_columns=[TableReference(table_schema='public', table_name='message', column_name='author_role')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='messagerole',
        new_values=['USER', 'SYSTEM'],
        affected_columns=[TableReference(table_schema='public', table_name='message', column_name='author_role')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
