"""RenameMetadataColumnToMeta

Revision ID: b3366018f2cb
Revises: 928913bf2430
Create Date: 2025-08-31 18:32:44.348160

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3366018f2cb'
down_revision: Union[str, Sequence[str], None] = '928913bf2430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('meta', sa.JSON(), nullable=True))
    op.drop_column('document', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('document', 'meta')
    # ### end Alembic commands ###
