"""Constantes do sistema Mar.IA."""

from backend.constants.prompts import (
    RAG_CHUNK_CONTEXT_TEMPLATE,
    RAG_DIRECT_RESPONSE_PROMPT,
    RAG_SYSTEM_PROMPT,
    RAG_USER_PROMPT_TEMPLATE,
    USER_INPUT_EVALUATION_PROMPT,
)

__all__ = [
    "RAG_SYSTEM_PROMPT",
    "RAG_USER_PROMPT_TEMPLATE",
    "RAG_CHUNK_CONTEXT_TEMPLATE",
    "RAG_DIRECT_RESPONSE_PROMPT",
    "USER_INPUT_EVALUATION_PROMPT"
]
