"""Add message entity and relationships

Revision ID: fa2967800fc5
Revises: 963d00ee4e23
Create Date: 2025-11-02 12:55:42.154165

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector




# revision identifiers, used by Alembic.
revision: str = 'fa2967800fc5'
down_revision: Union[str, Sequence[str], None] = '963d00ee4e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
    sa.Column('author_role', sa.Enum('USER', 'SYSTEM', name='messagerole'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_author_role', 'message', ['author_role'], unique=False)
    op.create_index('ix_message_user_created', 'message', ['user_id', 'created_at'], unique=False)
    op.create_table('message_chunk',
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunk.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'chunk_id')
    )
    op.add_column('session', sa.Column('fk_session_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('session_user_id_fkey'), 'session', type_='foreignkey')
    op.create_foreign_key(None, 'session', 'user', ['fk_session_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('session', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.create_foreign_key(op.f('session_user_id_fkey'), 'session', 'user', ['user_id'], ['id'])
    op.drop_column('session', 'fk_session_user_id')
    op.drop_table('message_chunk')
    op.drop_index('ix_message_user_created', table_name='message')
    op.drop_index('ix_message_author_role', table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
